2024-03-23 23:18:42,034 (98477/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-23 23:18:42,035 (98477/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-23 23:18:42,037 (98477/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection is bad: No such file or directory\n\tIs the server running locally and accepting connections on that socket?\n'
2024-03-23 23:19:38,152 (98495/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-23 23:19:38,153 (98495/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-23 23:19:38,191 (98495/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "defaultdb" does not exist\n'
2024-03-23 23:19:46,327 (98500/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-23 23:19:46,327 (98500/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-23 23:19:46,352 (98500/MainThread) pgcli.main ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 674, in connect\n    raise e\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/main.py", line 661, in connect\n    pgexecute = PGExecute(database, user, passwd, host, port, dsn, **kwargs)\n                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 181, in __init__\n    self.connect(database, user, password, host, port, dsn, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 230, in connect\n    conn = psycopg.connect(conn_info)\n           ^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/connection.py", line 748, in connect\n    raise last_ex.with_traceback(None)\npsycopg.OperationalError: connection failed: FATAL:  database "dbdefault" does not exist\n'
2024-03-23 23:20:10,081 (98659/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-23 23:20:10,082 (98659/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
2024-03-23 23:20:45,139 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'show tables', error: UndefinedObject('unrecognized configuration parameter "tables"')
2024-03-23 23:20:45,141 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.UndefinedObject: unrecognized configuration parameter "tables"\n'
2024-03-23 23:20:46,727 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'show table', error: SyntaxError('syntax error at or near "table"\nLINE 1: show table\n             ^')
2024-03-23 23:20:46,728 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "table"\nLINE 1: show table\n             ^\n'
2024-03-23 23:21:29,099 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'drop _user', error: SyntaxError('syntax error at or near "_user"\nLINE 1: drop _user\n             ^')
2024-03-23 23:21:29,100 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "_user"\nLINE 1: drop _user\n             ^\n'
2024-03-23 23:22:08,500 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'drop table _users', error: DependentObjectsStillExist('cannot drop table _users because other objects depend on it\nDETAIL:  constraint fk85gmnxt6adcei7qcmwce3cjto on table user_friends depends on table _users\nconstraint fkno23q7unmvtkb35g160asfw09 on table user_requests depends on table _users\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.')
2024-03-23 23:22:08,503 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DependentObjectsStillExist: cannot drop table _users because other objects depend on it\nDETAIL:  constraint fk85gmnxt6adcei7qcmwce3cjto on table user_friends depends on table _users\nconstraint fkno23q7unmvtkb35g160asfw09 on table user_requests depends on table _users\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n'
2024-03-23 23:22:23,046 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'drop table _users', error: DependentObjectsStillExist('cannot drop table _users because other objects depend on it\nDETAIL:  constraint fk85gmnxt6adcei7qcmwce3cjto on table user_friends depends on table _users\nconstraint fkno23q7unmvtkb35g160asfw09 on table user_requests depends on table _users\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.')
2024-03-23 23:22:23,048 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.DependentObjectsStillExist: cannot drop table _users because other objects depend on it\nDETAIL:  constraint fk85gmnxt6adcei7qcmwce3cjto on table user_friends depends on table _users\nconstraint fkno23q7unmvtkb35g160asfw09 on table user_requests depends on table _users\nHINT:  Use DROP ... CASCADE to drop the dependent objects too.\n'
2024-03-23 23:23:36,287 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table user', error: SyntaxError('syntax error at or near "user"\nLINE 1: create table user\n                     ^')
2024-03-23 23:23:36,289 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: create table user\n                     ^\n'
2024-03-23 23:23:42,170 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table _user', error: SyntaxError('syntax error at end of input\nLINE 1: create table _user\n                          ^')
2024-03-23 23:23:42,171 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at end of input\nLINE 1: create table _user\n                          ^\n'
2024-03-23 23:23:57,195 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table user {', error: SyntaxError('syntax error at or near "user"\nLINE 1: create table user {\n                     ^')
2024-03-23 23:23:57,196 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: create table user {\n                     ^\n'
2024-03-23 23:24:42,695 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table user {\nusername varchar(50),\npassword varchar(50)\n}', error: SyntaxError('syntax error at or near "user"\nLINE 1: create table user {\n                     ^')
2024-03-23 23:24:42,695 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "user"\nLINE 1: create table user {\n                     ^\n'
2024-03-23 23:24:50,607 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table -user {\nusername varchar(50),\npassword varchar(50)\n}', error: SyntaxError('syntax error at or near "-"\nLINE 1: create table -user {\n                     ^')
2024-03-23 23:24:50,608 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "-"\nLINE 1: create table -user {\n                     ^\n'
2024-03-23 23:24:58,685 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table _user {\nusername varchar(50),\npassword varchar(50)\n}', error: SyntaxError('syntax error at or near "{"\nLINE 1: create table _user {\n                           ^')
2024-03-23 23:24:58,686 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "{"\nLINE 1: create table _user {\n                           ^\n'
2024-03-23 23:29:30,774 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table posts (\nid SERIAL primary key,\ntitle varchar(255),\nhidden boolean default false,\ncontent varchar(500),\n)', error: SyntaxError('syntax error at or near ")"\nLINE 6: )\n        ^')
2024-03-23 23:29:30,775 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near ")"\nLINE 6: )\n        ^\n'
2024-03-23 23:31:38,844 (98659/MainThread) pgcli.pgexecute ERROR - sql: 'create table users (\nusername VARCHAR(50) primary key,\npassword varchar(50) primary key,\nis_admin boolean default false\n)', error: InvalidTableDefinition('multiple primary keys for table "users" are not allowed\nLINE 3: password varchar(50) primary key,\n                             ^')
2024-03-23 23:31:38,844 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.InvalidTableDefinition: multiple primary keys for table "users" are not allowed\nLINE 3: password varchar(50) primary key,\n                             ^\n'
2024-03-23 23:45:06,337 (98659/MainThread) pgcli.pgexecute ERROR - sql: "insert into users (username, password, is_admin)\nvalue ('admin', 'verySecurePassword=))', true)", error: SyntaxError('syntax error at or near "value"\nLINE 2: value (\'admin\', \'verySecurePassword=))\', true)\n        ^')
2024-03-23 23:45:06,338 (98659/MainThread) pgcli.pgexecute ERROR - traceback: 'Traceback (most recent call last):\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 395, in run\n    yield self.execute_normal_sql(sql) + (sql, True, False)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 445, in execute_normal_sql\n    cur.execute(split_sql)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/pgcli/pgexecute.py", line 90, in execute\n    super().execute(*args, **kwargs)\n  File "/opt/homebrew/Cellar/pgcli/4.0.1/libexec/lib/python3.12/site-packages/psycopg/cursor.py", line 732, in execute\n    raise ex.with_traceback(None)\npsycopg.errors.SyntaxError: syntax error at or near "value"\nLINE 2: value (\'admin\', \'verySecurePassword=))\', true)\n        ^\n'
2024-03-24 11:04:46,286 (3430/MainThread) pgcli.main INFO - Default pager found in PAGER environment variable: "less"
2024-03-24 11:04:46,287 (3430/MainThread) pgcli.main WARNING - import keyring failed: ModuleNotFoundError("No module named 'keyring'").
